### ISSUE TITLE
Magento hangs when Kiyoh is unreachable

### ISSUE THREAD

**Issue by gerben86** [Interactivated/kiyoh_magento2#11]
Kiyoh has a lot of issues lately (they are more down then up).
So it would make sense to make use of a Curl config which doesn't wait for 1 minute, but only for a couple of ms and then just skips the Kiyoh-call: 
https://github.com/Interactivated/kiyoh_magento2/blob/dfc20cff1c30e2eda213f5797b20012b86d12c63/Block/Customerreview.php#L72

I think it would be wise to add: curl_setopt($ch, CURLOPT_CONNECTTIMEOUT_MS, 100)
Because at this moment my webshop is responding after **1 minute** if Kiyoh isn't reachable and the page wasn't cached yet.

**Comment by Ronald-IE** [comment]
We've created internal ticket KIYOH-170 to address this issue.

**Comment by Ronald-IE** [comment]
Fixed with #13
