### ISSUE TITLE
Update Packagist.org

### ISSUE THREAD

**Issue by peterjaap** [Interactivated/kiyoh_magento2#16]
2.1.25 is still the latest version there instead of 2.1.26; https://packagist.org/packages/interactivated/customerreview

**Comment by Ronald-IE** [comment]
Hi @peterjaap, thanks for the heads up. @Radishok, please update the package.

**Comment by artemskyi** [comment]
@peterjaap @Ronald-IE 
the latest version is now set to 2.1.26.
