### ISSUE TITLE
Microdata doesn't adhere to Google standards

### ISSUE THREAD

**Issue by gerben86** [Interactivated/kiyoh_magento2#17]
According to an update of Google the WebPage type can't be used anymore: https://webmasters.googleblog.com/2019/09/making-review-rich-results-more-helpful.html

So another type should be referenced here:
https://github.com/Interactivated/kiyoh_magento2/blob/60b3c166d0f55aedbbd891c0c7783c52b772017b/view/frontend/templates/microdata.phtml#L27

Do you know what type this should be?

This leads to those 2 errors in the StructuredDataTestingTool:
![image](https://user-images.githubusercontent.com/17478858/66750322-7490f580-ee8c-11e9-8040-0b2f12171c54.png)

**Comment by Ronald-IE** [comment]
@gerben86, as it looks now Google won't allow reviews in this style at all.
See the part about "Self-serving reviews aren't allowed for LocalBusiness and Organization" and the update under it.
