### ISSUE TITLE
Not all shipments lead to a send reviewinvite

### ISSUE THREAD

**Issue by gerben86** [Interactivated/kiyoh_magento2#18]
On certain days I send 10 orders, but in the Kiyoh.com backend I only see 9 send invitations.
So it looks like that not all mailadresses are send to Kiyoh for a review, or that Kiyoh doesn't send a review for each mailadres.

Do you know how to debug this?
Is it possible to log the request and reply of the Kiyoh so I can track if the issue is in the extension or at Kiyoh-side?

**Comment by Ronald-IE** [comment]
Hello @gerben86, is it possible the one not getting an invite already received one in the recent period? I think Kiyoh will refuse to send an invite if the address received in one in the last month, might be longer.

I've opened an internal ticket to look into an error logging option: KIYOH-184

**Comment by gerben86** [comment]
Hello @Ronald-IE ,

I don't expect that it's due to already used mailadresses etc. Because at this moment I'm even missing a complete day. There are no invitations send for all shipments of last saturday. While they should be send after 4 days.
So it would be good to have some tracing/logging to see if the issue is on my on Kiyoh's side (I wouldn't be suprised if it's at their side...).

**Comment by gerben86** [comment]
@Ronald-IE : I did some more checks, and it looks like that a space in the lastname of the customer caused this issue. After updating the AbstractObserver.php to the latest version it looks like that the issue is solved.
The only strange thing I see is that only curl-errors are logged if the debug is enabled. I guess it would make sense to log curl-errors on and error-level instead of debug-level.

**Comment by Ronald-IE** [comment]
@gerben86, good to hear you managed to find the problem. Issue with spacing was indeed fixed in #15 

I'll add your point about curl-errors to internal ticket KIYOH-184
