### ISSUE TITLE
Review aggregates (averages and total number) aren't updated anymore

### ISSUE THREAD

**Issue by peterjaap** [Interactivated/kiyoh_magento2#24]
Review aggregates aren't updating because the XML at this URL isn't updated anymore by Kiyoh; https://github.com/Interactivated/kiyoh_magento2/blob/84137c7c6e3d1a05a27ef010fda59bde8fbbcaff/Block/Customerreview.php#L113

**Comment by peterjaap** [comment]
Example of a correct URL: https://www.kiyoh.com/v1/review/feed.xml?hash=k497xxsprtc8mmh

**Comment by gjportegies** [comment]
Any progress on this? I'm experiencing the same issues.

I've changed the following lines with the link @peterjaap mentioned. Only changes it to the json feed. Also the company is not provided by the feed anymore.

```
//                        $url = "https://{$server}/v1/publication/review/external/location/statistics?locationId=" . $location_id;
                        $url = "https://{$server}/v1/review/feed.json?hash=" . $hash;
                        $ch = curl_init();

                        // set url
                        curl_setopt($ch, CURLOPT_URL, $url);
//                        curl_setopt($ch, CURLOPT_HTTPHEADER, [
//                            'X-Publication-Api-Token: ' . $hash
//                        ]);
                        //return the transfer as a string
                        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                        curl_setopt($ch, CURLOPT_TIMEOUT, 1);
                        // $output contains the output string
                        $output = curl_exec($ch);
```

**Comment by peterjaap** [comment]
We needed a working extension so we wrote our own:
https://github.com/elgentos/magento2 Kiyoh

**Comment by Radishok** [comment]
It is old kiyoh server connector left to backward compatibility. Please use option "Klantenvertellen.nl & new kiyoh.com"
![изображение](https://user-images.githubusercontent.com/888988/91305149-46ba5400-e7b3-11ea-8bb5-0ade16a55974.png)

**Comment by cowoder** [comment]
To complete the information in this ticket as there seems to be some confusion.

I've double checked this with Kiyoh today. They confirm the module is using the correct url (api version, not xml feed).
Kiyoh suggests the wrong hash is being used for your settings if it doesn't work, the xml feed uses a different hash than the api.

With the correct config this url is used:
https://github.com/Interactivated/kiyoh_magento2/blob/01a3d17c75af882a37ee9c3fbdd37d6d11cbbc34/Block/Customerreview.php#L67

The old config uses:
https://github.com/Interactivated/kiyoh_magento2/blob/01a3d17c75af882a37ee9c3fbdd37d6d11cbbc34/Block/Customerreview.php#L114

Also see #27

**Comment by mdevrees** [comment]
@cowoder Thanks, that was my issue, the wrong hash was used. When using the api hash from invites > extra options, I now get a correct response.
