### ISSUE TITLE
Deprecated URLs which fails to fetch data

### ISSUE THREAD

**Issue by mdevrees** [Interactivated/kiyoh_magento2#27]
The kiyoh urls as used in the module are deprecated, according to [Kiyoh helpcenter docs](https://sngj8ctfe5nk7qmfb.polly.help/topic/8nurd8HdTDZPju3D8/article/9fGLjyLbbe8JJjHBa) the url is now 
```
XML-feed:
Verouderde methode: http://www.klantenvertellen.nl/xml/bedrijfsnaam/
Nieuwe juiste weergave: https://www.klantenvertellen.nl/v1/review/feed.xml?hash=XXX
```
You can also replace feed.xml with feed.json to get a json response. 

The old urls somehow always result in a message saying "Company not found" while the company definitely is there.
Using the new feed.json url it works:
![Screenshot from 2020-11-19 12-28-59-1](https://user-images.githubusercontent.com/1950480/99661032-89629400-2a63-11eb-8d4a-4bfd77305c43.png)
![Screenshot from 2020-11-19 12-34-29](https://user-images.githubusercontent.com/1950480/99661078-9bdccd80-2a63-11eb-93a9-a83a7900e1de.png)

Could you guys doublecheck and update the urls?

**Comment by cowoder** [comment]
The module uses the api, not the xml feed. But I've contacted Kiyoh to double check this.

**Comment by mdevrees** [comment]
Alright thanks, let me know if it helps. I just double checked the api and the response I always get is unauthorized:
![Screenshot from 2020-11-19 13-03-17-1](https://user-images.githubusercontent.com/1950480/99664141-06900800-2a68-11eb-8f53-17c1941bc6c1.png)
Is there a setting that needs to be enabled in the Kiyoh account in order to use this? LocationID and hash are correct.

**Comment by cowoder** [comment]
I'm unaware of any settings affecting this. I have found a locationId that isn't working on the api, but another one that does work, so I've shared these examples with Kiyoh to check on their end.

**Comment by cowoder** [comment]
@mdevrees, Kiyoh confirms the api in the module should work fine and asks if you can contact them directly to confirm the locationId and hash you're using.

**Comment by mdevrees** [comment]
@cowoder thanks for your input, I've contacted Kiyoh directly and will wait for their response. Thanks for the quick responses, I'll check it with them now.

**Comment by cowoder** [comment]
For future readers.

I think I've found the source of the not working hash confusion, see comment I just wrote here: https://github.com/Interactivated/kiyoh_magento2/issues/24#issuecomment-730508055
