### ISSUE TITLE
composer require fails

### ISSUE THREAD

**Issue by hans2103** [Interactivated/kiyoh_magento2#32]
```
composer require interactivated\/customerreview 
```

it will give the following exception. 

>  [Exception]                                                                                                                                    
>   Higher matching version 2.1.30 of interactivated/customerreview was found in public repository packagist.org than 2.1.29 in private https://repo.magento.com. Public package might've been taken over by a malicious entity, please investigate and update package requirement to match the version from the private repository                

I would like to install interactivated\/customerreview using composer

**Comment by cowoder** [comment]
@Radishok, we need to update version number in packagist to resolve this error. Can you take care of that, please?

**Comment by hans2103** [comment]
@Radishok can this be done in the near future? It's the last thing we have to implement / test before we can finish migrating M1 => M2

**Comment by hans2103** [comment]
@Radishok can this be done in the near future? It's the last thing we have to implement / test before we can finish migrating M1 => M2

**Comment by cowoder** [comment]
New version has been submitted, pending approval from Magento Marketplace

**Comment by cowoder** [comment]
Status says approved, but for some reason isn't listed yet. I've given them a push, hopefully it helps
