### ISSUE TITLE
Error when registering

### ISSUE THREAD

**Issue by tsukasa1989** [Interactivated/kiyoh_magento2#35]
We have setup the connection following the instructions, but customers are not added to Kiyoh. We are getting the following error in the plugin logs:

```

2022-07-11T09:10:51+00:00 INFO (6): {
  "httpCode" : 400,
  "errorCode" : "INTERNAL_SERVER_ERROR",
  "id" : "a8c7941f-8ebe-4971-9854-16e33805b2f0",
  "detailedError" : [ {
    "errorCode" : "EMAIL_DOMAIN_DOES_NOT_EXIST",
    "message" : "Mail server is out of reach or does not exist."
  } ]
}

```

I have double checked the api key, location id, etc. And it's all setup correctly.

**Comment by tsukasa1989** [comment]
Any help on this would be appreciated.

**Comment by cowoder** [comment]
@tsukasa1989, hard to tell from that error, because the plugin doesn't send any e-mails itself. Could you please e-mail suzanna[at]interactivated[dot]me, she'll try to help you further.
